import 'package:get_it/get_it.dart';
import 'package:storecs/features/auth/presentation/state_management/sign_in_controller.dart';
import 'package:storecs/features/auth/presentation/state_management/sign_out_controller.dart';
import 'package:storecs/features/auth/presentation/state_management/sign_up_controller.dart';
import 'package:storecs/features/dash_board/presentation/state_management/fetch_category_dashboard_controller.dart';
import 'package:storecs/features/dash_board/presentation/state_management/fetch_employee_info_dash_board_controller.dart';
import 'package:storecs/features/feedback_page/presentation/state_management/get_feedback_controller.dart';
import 'package:storecs/features/issues_or_suggestions/presentation/state_management/feedback_controller.dart';
import 'package:storecs/features/order_purchased_history/presentation/state_management/order_purchased_history_controller.dart';
import 'package:storecs/features/pos_page/presentation/state_management/cart_controller.dart';
import 'package:storecs/features/pos_page/presentation/state_management/pos_controller.dart';
import 'package:storecs/features/product_list/presentation/state_management/product_list_controller.dart';
import 'package:storecs/features/report_page/presentation/state_management/report_controller.dart';
import 'package:storecs/features/returns&refunds/presentation/state_management/return_and_refund_controller.dart';
import 'package:storecs/features/settings_page/presentation/state_management/product_matrix_controller.dart';
import 'package:storecs/features/settings_page/presentation/state_management/tax_rules_controller.dart';
import 'package:storecs/features/staff_list/presentation/state_management/staff_list_controller.dart';

final sl = GetIt.instance;
final signInController = sl<SignInController>();
final signUpController = sl<SignUpController>();
final signOutController = sl<SignOutController>();
final fetchEmployeeInfoDashBoardController =
    sl<FetchEmployeeInfoDashBoardController>();
final staffListController = sl<StaffListController>();
final productListController = sl<ProductListController>();
final posController = sl<PosController>();
final cartController = sl<CartController>();
final orderPurchasedHistoryController = sl<OrderPurchasedHistoryController>();
final returnAndRefundController = sl<ReturnAndRefundController>();
final reportController = sl<ReportController>();
final fetchCategoryDashboardController = sl<FetchCategoryDashboardController>();
final feedbackController = sl<FeedbackController>();
final getFeedbackController = sl<GetFeedbackController>();
final taxRulesController = sl<TaxRulesController>();
final productMatrixController = sl<ProductMatrixController>();
