// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR5UHiVWMaYmDyMGQGYChTrMzpHgxPzQU',
    appId: '1:1094066154571:web:be7b6c22dfcbe5b07271ce',
    messagingSenderId: '1094066154571',
    projectId: 'electronic-store-46793',
    authDomain: 'electronic-store-46793.firebaseapp.com',
    storageBucket: 'electronic-store-46793.firebasestorage.app',
    measurementId: 'G-L0L3HL00D1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4rsfGANCNsOdClF75LPOoxlmgax9cp6s',
    appId: '1:1094066154571:android:3808e600e55923107271ce',
    messagingSenderId: '1094066154571',
    projectId: 'electronic-store-46793',
    storageBucket: 'electronic-store-46793.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ8cFexhLy5BlTpswzI1wVz9RPIhdiA7M',
    appId: '1:1094066154571:ios:aa4c44450e6b75777271ce',
    messagingSenderId: '1094066154571',
    projectId: 'electronic-store-46793',
    storageBucket: 'electronic-store-46793.firebasestorage.app',
    androidClientId: '1094066154571-1282r3p6u4bmsl2qce3q5hp5omu33ol2.apps.googleusercontent.com',
    iosClientId: '1094066154571-ioei51s9qkc171v8p1t2p4bkh5qlgho8.apps.googleusercontent.com',
    iosBundleId: 'com.example.storecs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ8cFexhLy5BlTpswzI1wVz9RPIhdiA7M',
    appId: '1:1094066154571:ios:aa4c44450e6b75777271ce',
    messagingSenderId: '1094066154571',
    projectId: 'electronic-store-46793',
    storageBucket: 'electronic-store-46793.firebasestorage.app',
    androidClientId: '1094066154571-1282r3p6u4bmsl2qce3q5hp5omu33ol2.apps.googleusercontent.com',
    iosClientId: '1094066154571-ioei51s9qkc171v8p1t2p4bkh5qlgho8.apps.googleusercontent.com',
    iosBundleId: 'com.example.storecs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR5UHiVWMaYmDyMGQGYChTrMzpHgxPzQU',
    appId: '1:1094066154571:web:af679f4fc66935c17271ce',
    messagingSenderId: '1094066154571',
    projectId: 'electronic-store-46793',
    authDomain: 'electronic-store-46793.firebaseapp.com',
    storageBucket: 'electronic-store-46793.firebasestorage.app',
    measurementId: 'G-RG2JRZG1MW',
  );
}
